# Assignment-5

In [1]:
import numpy as np

In [3]:
def arrays(arr):
    a = np.array(arr,dtype=float)
    return a[::-1]
arr = [2,5,7,3,6]
print(arrays(arr))

[6. 3. 7. 5. 2.]


In [5]:
arr = list(range(9))
arr = np.array(arr)
print(arr.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
n,m = map(int,input().split())
l = []
for i in range(n):
    a = list(map(int,input().split()))
    l.append(a)
l = np.array(l)
print(np.transpose(l))
print(l.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [8]:
t = tuple(map(int,input().split()))
print(np.zeros(t,dtype=int),np.ones(t,dtype=int),sep='\n')



2 2 2
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [9]:
n,m = [int(x) for x in input().split()]
print(np.eye(n,m))

3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
